; NSIS Hooks for LiMBo Desktop Installer
; Auto-generated by build-desktop.mjs

!include "nsDialogs.nsh"
!include "LogicLib.nsh"

Var PremiereDialog
Var PremiereCheckbox
Var PremiereCheckboxState
Var PremiereDetected
Var PremiereInitDone

Function InitPremiereDetection
  ${If} $PremiereInitDone != 1
    StrCpy $PremiereInitDone 1
    StrCpy $PremiereDetected 0
    StrCpy $PremiereCheckboxState 0

    ; 1. Check HKCU for Premiere Pro or Premiere Pro (Beta)
    ClearErrors
    ReadRegStr $0 HKCU "Software\Adobe\Premiere Pro" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ClearErrors
    ReadRegStr $0 HKCU "Software\Adobe\Premiere Pro (Beta)" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ; 2. Check HKLM for Premiere Pro or Premiere Pro (Beta)
    ClearErrors
    ReadRegStr $0 HKLM "Software\Adobe\Premiere Pro" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "Software\Adobe\Premiere Pro (Beta)" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Adobe Premiere Pro.exe" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Adobe Premiere Pro (Beta).exe" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ; 3. Check WOW6432Node
    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\WOW6432Node\Adobe\Premiere Pro" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\WOW6432Node\Adobe\Premiere Pro (Beta)" ""
    ${IfNot} ${Errors}
      StrCpy $PremiereDetected 1
    ${EndIf}

    ; 4. Check AppData folder
    ${If} ${FileExists} "$APPDATA\Adobe\Premiere Pro\*.*"
      StrCpy $PremiereDetected 1
    ${EndIf}
    ${If} ${FileExists} "$APPDATA\Adobe\Premiere Pro (Beta)\*.*"
      StrCpy $PremiereDetected 1
    ${EndIf}

    ; Default state: checked if detected, unchecked otherwise
    ${If} $PremiereDetected = 1
      StrCpy $PremiereCheckboxState 1
    ${Else}
      StrCpy $PremiereCheckboxState 0
    ${EndIf}
  ${EndIf}
FunctionEnd

Function PremierePageCreate
  ; Skip in silent mode
  ${If} ${Silent}
    Abort
  ${EndIf}

  Call InitPremiereDetection

  !insertmacro MUI_HEADER_TEXT "Composants additionnels" "Intégration Adobe Premiere Pro"

  nsDialogs::Create 1018
  Pop $PremiereDialog
  ${If} $PremiereDialog == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 10u 100% 25u "LiMBo propose un panneau d'intégration pour Adobe Premiere Pro (panneau CEP) permettant d'importer directement vos médias téléchargés dans votre projet ou sur votre timeline."
  Pop $0

  ${If} $PremiereDetected = 1
    ${NSD_CreateLabel} 0 45u 100% 15u "✓ Adobe Premiere Pro (ou Premiere Pro Beta) a été détecté sur cet ordinateur."
    Pop $0
  ${Else}
    ${NSD_CreateLabel} 0 45u 100% 15u "ℹ Adobe Premiere Pro n'a pas été détecté sur cet ordinateur."
    Pop $0
  ${EndIf}

  ${NSD_CreateCheckbox} 10u 70u 95% 15u "Installer et activer l'extension LiMBo pour Adobe Premiere Pro (panneau CEP)"
  Pop $PremiereCheckbox

  ${If} $PremiereCheckboxState = 1
    ${NSD_Check} $PremiereCheckbox
  ${Else}
    ${NSD_Uncheck} $PremiereCheckbox
  ${EndIf}

  nsDialogs::Show
FunctionEnd

Function PremierePageLeave
  ${NSD_GetState} $PremiereCheckbox $PremiereCheckboxState
FunctionEnd

Page custom PremierePageCreate PremierePageLeave

!macro NSIS_HOOK_POSTINSTALL
  ; 1. Install sidecar binaries (yt-dlp.exe, ffmpeg.exe) directly into $INSTDIR
  SetOutPath "$INSTDIR"
  File /nonfatal "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\bin\yt-dlp.exe"
  File /nonfatal "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\bin\ffmpeg.exe"

  ; 2. Install Chromium extension files into $INSTDIR\extension\chromium
  SetOutPath "$INSTDIR\extension\chromium"
  File /nonfatal /r "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\extension\*.*"

  ; 3. Install Firefox extension files (.xpi & unpacked) into $INSTDIR\extension\firefox
  SetOutPath "$INSTDIR\extension\firefox"
  File /nonfatal /r "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\firefox\*.*"

  ; 4. Install Adobe Premiere Pro CEP extension if checkbox was checked
  Call InitPremiereDetection
  ${If} $PremiereCheckboxState == 1
    SetOutPath "$INSTDIR\extension\premiere"
    File /nonfatal /r "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\premiere\*.*"

    SetOutPath "$APPDATA\Adobe\CEP\extensions\LiMBO-premiere"
    File /nonfatal /r "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\prod\premiere\*.*"

    ; Enable PlayerDebugMode so Premiere loads unsigned CEP extensions without prompts (CSXS.9 à CSXS.16)
    WriteRegStr HKCU "Software\Adobe\CSXS.9" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.9.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.10" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.10.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.11" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.11.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.12" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.12.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.13" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.13.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.14" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.14.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.15" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.15.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.16" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\Adobe\CSXS.16.0" "PlayerDebugMode" "1"
  ${EndIf}

  ; 5. Install HTML visual onboarding guide into $INSTDIR\extension
  SetOutPath "$INSTDIR\extension"
  File /nonfatal "F:\DBXSSD\Dropbox\FOUTOIR\vibecoding\extension video downloader\dev\apps\extension\install-instructions.html"

  ; 6. Ensure Desktop shortcut is always created
  Call CreateOrUpdateDesktopShortcut

  ; 7. Propose adding extension to Chromium and Firefox
  ${IfNot} ${Silent}
    ${If} $PremiereCheckboxState == 1
      MessageBox MB_YESNO|MB_ICONQUESTION "LiMBo a été installé avec succès !$\r$\n$\r$\nL'extension Premiere Pro a été configurée dans Adobe CEP.$\r$\n$\r$\nSouhaitez-vous ouvrir les instructions pour activer l'extension LiMBo dans votre navigateur (Chrome / Firefox) ?" IDNO skip_ext_prompt_pr
        ExecShell "open" "$INSTDIR\extension\install-instructions.html"
      skip_ext_prompt_pr:
    ${Else}
      MessageBox MB_YESNO|MB_ICONQUESTION "LiMBo a été installé avec succès !$\r$\n$\r$\nSouhaitez-vous ouvrir les instructions pour activer l'extension LiMBo dans votre navigateur (Chrome / Firefox) ?" IDNO skip_ext_prompt_nopr
        ExecShell "open" "$INSTDIR\extension\install-instructions.html"
      skip_ext_prompt_nopr:
    ${EndIf}
  ${EndIf}
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  ; Clean up extra installed files before uninstall
  Delete "$INSTDIR\yt-dlp.exe"
  Delete "$INSTDIR\ffmpeg.exe"
  RMDir /r "$INSTDIR\extension"
  RMDir /r "$APPDATA\Adobe\CEP\extensions\LiMBO-premiere"
!macroend
