// Builds the Tauri desktop app in release mode and copies ONLY the resulting standalone
// installer bundle (LiMBo-Installer.exe) into `prod/desktop/`.
//
// Usage: node scripts/build-desktop.mjs (from `dev/`, or via `pnpm build`)

import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { homedir, platform } from "node:os";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const repo = path.resolve(root, "..");
const desktopDir = path.join(root, "apps", "desktop");
const srcTauriDir = path.join(desktopDir, "src-tauri");
const out = path.join(repo, "prod", "desktop");

// 1. Terminate running limbo-desktop instances so files in prod/desktop/ are not locked
if (platform() === "win32") {
  try {
    spawnSync("taskkill", ["/F", "/IM", "limbo-desktop.exe"], { stdio: "ignore" });
  } catch {}
}

// 2. Dynamically generate nsis_hooks.nsh with absolute paths to ensure NSIS makensis finds files
const ytdlpPath = path.join(repo, "prod", "bin", "yt-dlp.exe");
const ffmpegPath = path.join(repo, "prod", "bin", "ffmpeg.exe");
const extCrPath = path.join(repo, "prod", "extension");
const extFfPath = path.join(repo, "prod", "firefox");
const extPremierePath = path.join(repo, "prod", "premiere");
const guidePath = path.join(root, "apps", "extension", "install-instructions.html");

const nsisHooksContent = `; NSIS Hooks for LiMBo Desktop Installer
; Auto-generated by build-desktop.mjs

!include "nsDialogs.nsh"
!include "LogicLib.nsh"

Var PremiereDialog
Var PremiereCheckbox
Var PremiereCheckboxState
Var PremiereDetected
Var PremiereInitDone

Function InitPremiereDetection
  \${If} $PremiereInitDone != 1
    StrCpy $PremiereInitDone 1
    StrCpy $PremiereDetected 0
    StrCpy $PremiereCheckboxState 0

    ; 1. Check HKCU for Premiere Pro or Premiere Pro (Beta)
    ClearErrors
    ReadRegStr $0 HKCU "Software\\Adobe\\Premiere Pro" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ClearErrors
    ReadRegStr $0 HKCU "Software\\Adobe\\Premiere Pro (Beta)" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ; 2. Check HKLM for Premiere Pro or Premiere Pro (Beta)
    ClearErrors
    ReadRegStr $0 HKLM "Software\\Adobe\\Premiere Pro" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "Software\\Adobe\\Premiere Pro (Beta)" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\Adobe Premiere Pro.exe" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\Adobe Premiere Pro (Beta).exe" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ; 3. Check WOW6432Node
    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\\WOW6432Node\\Adobe\\Premiere Pro" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ClearErrors
    ReadRegStr $0 HKLM "SOFTWARE\\WOW6432Node\\Adobe\\Premiere Pro (Beta)" ""
    \${IfNot} \${Errors}
      StrCpy $PremiereDetected 1
    \${EndIf}

    ; 4. Check AppData folder
    \${If} \${FileExists} "$APPDATA\\Adobe\\Premiere Pro\\*.*"
      StrCpy $PremiereDetected 1
    \${EndIf}
    \${If} \${FileExists} "$APPDATA\\Adobe\\Premiere Pro (Beta)\\*.*"
      StrCpy $PremiereDetected 1
    \${EndIf}

    ; Default state: checked if detected, unchecked otherwise
    \${If} $PremiereDetected = 1
      StrCpy $PremiereCheckboxState 1
    \${Else}
      StrCpy $PremiereCheckboxState 0
    \${EndIf}
  \${EndIf}
FunctionEnd

Function PremierePageCreate
  ; Skip in silent mode
  \${If} \${Silent}
    Abort
  \${EndIf}

  Call InitPremiereDetection

  !insertmacro MUI_HEADER_TEXT "Composants additionnels" "Intégration Adobe Premiere Pro"

  nsDialogs::Create 1018
  Pop $PremiereDialog
  \${If} $PremiereDialog == error
    Abort
  \${EndIf}

  \${NSD_CreateLabel} 0 10u 100% 25u "LiMBo propose un panneau d'intégration pour Adobe Premiere Pro (panneau CEP) permettant d'importer directement vos médias téléchargés dans votre projet ou sur votre timeline."
  Pop $0

  \${If} $PremiereDetected = 1
    \${NSD_CreateLabel} 0 45u 100% 15u "✓ Adobe Premiere Pro (ou Premiere Pro Beta) a été détecté sur cet ordinateur."
    Pop $0
  \${Else}
    \${NSD_CreateLabel} 0 45u 100% 15u "ℹ Adobe Premiere Pro n'a pas été détecté sur cet ordinateur."
    Pop $0
  \${EndIf}

  \${NSD_CreateCheckbox} 10u 70u 95% 15u "Installer et activer l'extension LiMBo pour Adobe Premiere Pro (panneau CEP)"
  Pop $PremiereCheckbox

  \${If} $PremiereCheckboxState = 1
    \${NSD_Check} $PremiereCheckbox
  \${Else}
    \${NSD_Uncheck} $PremiereCheckbox
  \${EndIf}

  nsDialogs::Show
FunctionEnd

Function PremierePageLeave
  \${NSD_GetState} $PremiereCheckbox $PremiereCheckboxState
FunctionEnd

Page custom PremierePageCreate PremierePageLeave

!macro NSIS_HOOK_POSTINSTALL
  ; 1. Install sidecar binaries (yt-dlp.exe, ffmpeg.exe) directly into $INSTDIR
  SetOutPath "$INSTDIR"
  File /nonfatal "${ytdlpPath}"
  File /nonfatal "${ffmpegPath}"

  ; 2. Install Chromium extension files into $INSTDIR\\extension\\chromium
  SetOutPath "$INSTDIR\\extension\\chromium"
  File /nonfatal /r "${extCrPath}\\*.*"

  ; 3. Install Firefox extension files (.xpi & unpacked) into $INSTDIR\\extension\\firefox
  SetOutPath "$INSTDIR\\extension\\firefox"
  File /nonfatal /r "${extFfPath}\\*.*"

  ; 4. Install Adobe Premiere Pro CEP extension if checkbox was checked
  Call InitPremiereDetection
  \${If} $PremiereCheckboxState == 1
    SetOutPath "$INSTDIR\\extension\\premiere"
    File /nonfatal /r "${extPremierePath}\\*.*"

    SetOutPath "$APPDATA\\Adobe\\CEP\\extensions\\LiMBO-premiere"
    File /nonfatal /r "${extPremierePath}\\*.*"

    ; Enable PlayerDebugMode so Premiere loads unsigned CEP extensions without prompts (CSXS.9 à CSXS.16)
    WriteRegStr HKCU "Software\\Adobe\\CSXS.9" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.9.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.10" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.10.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.11" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.11.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.12" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.12.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.13" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.13.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.14" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.14.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.15" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.15.0" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.16" "PlayerDebugMode" "1"
    WriteRegStr HKCU "Software\\Adobe\\CSXS.16.0" "PlayerDebugMode" "1"
  \${EndIf}

  ; 5. Install HTML visual onboarding guide into $INSTDIR\\extension
  SetOutPath "$INSTDIR\\extension"
  File /nonfatal "${guidePath}"

  ; 6. Ensure Desktop shortcut is always created
  Call CreateOrUpdateDesktopShortcut

  ; 7. Propose adding extension to Chromium and Firefox
  \${IfNot} \${Silent}
    \${If} $PremiereCheckboxState == 1
      MessageBox MB_YESNO|MB_ICONQUESTION "LiMBo a été installé avec succès !$\\r$\\n$\\r$\\nL'extension Premiere Pro a été configurée dans Adobe CEP.$\\r$\\n$\\r$\\nSouhaitez-vous ouvrir les instructions pour activer l'extension LiMBo dans votre navigateur (Chrome / Firefox) ?" IDNO skip_ext_prompt_pr
        ExecShell "open" "$INSTDIR\\extension\\install-instructions.html"
      skip_ext_prompt_pr:
    \${Else}
      MessageBox MB_YESNO|MB_ICONQUESTION "LiMBo a été installé avec succès !$\\r$\\n$\\r$\\nSouhaitez-vous ouvrir les instructions pour activer l'extension LiMBo dans votre navigateur (Chrome / Firefox) ?" IDNO skip_ext_prompt_nopr
        ExecShell "open" "$INSTDIR\\extension\\install-instructions.html"
      skip_ext_prompt_nopr:
    \${EndIf}
  \${EndIf}
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  ; Clean up extra installed files before uninstall
  Delete "$INSTDIR\\yt-dlp.exe"
  Delete "$INSTDIR\\ffmpeg.exe"
  RMDir /r "$INSTDIR\\extension"
  RMDir /r "$APPDATA\\Adobe\\CEP\\extensions\\LiMBO-premiere"
!macroend
`;


writeFileSync(path.join(srcTauriDir, "nsis_hooks.nsh"), nsisHooksContent, "utf-8");



// 3. Run Tauri build
const result = spawnSync("pnpm", ["run", "tauri", "build"], {
  cwd: desktopDir,
  stdio: "inherit",
  shell: true,
});
if (result.status !== 0) {
  console.error("build-desktop: `tauri build` failed");
  process.exit(result.status ?? 1);
}

// 4. Locate Cargo target release dir
const cargoTargetDir =
  platform() === "win32"
    ? path.join(process.env.LOCALAPPDATA ?? path.join(homedir(), "AppData", "Local"), "limbo-desktop-cargo-target")
    : path.join(desktopDir, "src-tauri", "target");
const releaseDir = path.join(cargoTargetDir, "release");

try {
  rmSync(out, { recursive: true, force: true, maxRetries: 10, retryDelay: 500 });
  mkdirSync(out, { recursive: true });
} catch (e) {
  if (e.code === "EPERM" || e.code === "EBUSY") {
    console.warn("build-desktop: prod/desktop est verrouillé (LiMBo est probablement en cours d'exécution dans le tray).");
  } else {
    throw e;
  }
}

// Copy ONLY the standalone NSIS installer to prod/desktop/LiMBo-Installer.exe
// (Embeds limbo-desktop.exe, yt-dlp.exe, ffmpeg.exe, Chromium & Firefox extensions, and visual guide)
const bundleDir = path.join(releaseDir, "bundle");
const nsisDir = path.join(bundleDir, "nsis");
const pkg = JSON.parse(readFileSync(path.join(desktopDir, "package.json"), "utf-8"));
const expectedInstaller = `LiMBo_${pkg.version}_x64-setup.exe`;

let installerCopied = false;
if (existsSync(nsisDir)) {
  const srcInstaller = path.join(nsisDir, expectedInstaller);
  if (existsSync(srcInstaller)) {
    cpSync(srcInstaller, path.join(out, "LiMBo-Installer.exe"));
    installerCopied = true;
  } else {
    const exes = readdirSync(nsisDir).filter((file) => file.toLowerCase().endsWith(".exe"));
    if (exes.length > 0) {
      cpSync(path.join(nsisDir, exes[exes.length - 1]), path.join(out, "LiMBo-Installer.exe"));
      installerCopied = true;
    }
  }
}

if (installerCopied) {
  console.log(`[build-desktop] Installeur unique prêt à partager : ${path.join(out, "LiMBo-Installer.exe")}`);
} else {
  console.error(`build-desktop: aucun installeur trouvé dans ${nsisDir}`);
  process.exit(1);
}

console.log("Wrote", out);

