/** Builds a Netscape cookie file body for the given page URL (current browser session). */
export async function exportNetscapeCookies(pageUrl: string): Promise<string> {
  let parsed: URL;
  try {
    parsed = new URL(pageUrl);
  } catch {
    return "";
  }

  const byUrl = await chrome.cookies.getAll({ url: pageUrl });
  const byHost = await chrome.cookies.getAll({ domain: parsed.hostname });
  const parent = parentDomain(parsed.hostname);
  const byParent = parent
    ? await chrome.cookies.getAll({ domain: parent })
    : [];

  const merged = new Map<string, chrome.cookies.Cookie>();
  for (const cookie of [...byUrl, ...byHost, ...byParent]) {
    merged.set(`${cookie.domain}|${cookie.path}|${cookie.name}`, cookie);
  }

  if (merged.size === 0) {
    return "";
  }

  const lines = ["# Netscape HTTP Cookie File", "# Generated by LiMBo extension"];
  for (const cookie of merged.values()) {
    const domain = cookie.domain.startsWith(".")
      ? cookie.domain
      : cookie.hostOnly
        ? cookie.domain
        : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiry =
      cookie.expirationDate && Number.isFinite(cookie.expirationDate)
        ? Math.floor(cookie.expirationDate)
        : 0;
    lines.push(
      [
        domain,
        includeSubdomains,
        cookie.path || "/",
        secure,
        String(expiry),
        cookie.name,
        cookie.value,
      ].join("\t"),
    );
  }

  return lines.join("\n");
}

function parentDomain(hostname: string): string | null {
  const parts = hostname.split(".");
  if (parts.length < 3) return null;
  return parts.slice(1).join(".");
}
